name: onsetway_services
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.10.0
  shared_preferences: ^2.5.3
  awesome_bottom_bar: ^1.2.4
  http: ^1.5.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.3.0
  image_picker: ^1.2.0
  file_picker: ^10.3.2
  gradient_borders: ^1.0.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1   # أضِف الحزمة هنا

flutter:
  uses-material-design: true

  assets:
    - assets/video/
    - assets/logo/
    - assets/picture/
    - assets/programming/pos/
    - assets/programming/mobile app/
    - assets/programming/web/
    - assets/programming/desktop/
    - assets/hardware/cctv/
    - assets/hardware/pc/
    - assets/hardware/network/
    - assets/core/
    - assets/marketing/

  fonts:
    - family: Northwell
      fonts:
        - asset: assets/fonts/Northwell.ttf
    - family: MAIAN
      fonts:
        - asset: assets/fonts/MAIAN.TTF


flutter_native_splash:
  ios: true
  android: true
  color: "#000000"
  color_dark: "#000000"
  android_12:
    color: "#000000"
